name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      metadata: read
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: |
            # AWTRIX3 CLI v${{ steps.get_version.outputs.version }}
            
            A modern, async Rust CLI for controlling AWTRIX3 LED matrix displays.
            
            ## Installation
            
            ### From Binary
            Download the appropriate binary for your platform from the assets below.
            
            ### From Source
            ```bash
            cargo install awtrix3
            ```
            
            ## Changes
            See [CHANGELOG.md](https://github.com/jeremyeder/awtrix3-rs/blob/main/CHANGELOG.md) for detailed changes.
            
          draft: false
          prerelease: false

  build-release:
    name: Build Release
    needs: create-release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: awtrix3-linux-x86_64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: awtrix3-macos-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: awtrix3-macos-aarch64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: awtrix3-windows-x86_64.exe
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }} --all-features

      - name: Strip binary (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: strip target/${{ matrix.target }}/release/awtrix3

      - name: Generate shell completions
        run: |
          mkdir -p completions
          cargo run --release --target ${{ matrix.target }} -- completions bash > completions/awtrix3.bash
          cargo run --release --target ${{ matrix.target }} -- completions zsh > completions/_awtrix3
          cargo run --release --target ${{ matrix.target }} -- completions fish > completions/awtrix3.fish
          cargo run --release --target ${{ matrix.target }} -- completions powershell > completions/awtrix3.ps1

      - name: Create archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/awtrix3 dist/
          cp README.md LICENSE-MIT LICENSE-APACHE INSTALL.md dist/
          cp -r completions dist/
          cp -r examples dist/
          cd dist
          tar czf ../awtrix3-v${{ needs.create-release.outputs.version }}-${{ matrix.target }}.tar.gz *
          cd ..
          echo "ASSET_PATH=awtrix3-v${{ needs.create-release.outputs.version }}-${{ matrix.target }}.tar.gz" >> $GITHUB_ENV

      - name: Create archive (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir dist
          copy target\${{ matrix.target }}\release\awtrix3.exe dist\
          copy README.md dist\
          copy LICENSE-MIT dist\
          copy LICENSE-APACHE dist\
          copy INSTALL.md dist\
          xcopy completions dist\completions\ /E /I
          xcopy examples dist\examples\ /E /I
          cd dist
          7z a ..\awtrix3-v${{ needs.create-release.outputs.version }}-${{ matrix.target }}.zip *
          cd ..
          echo "ASSET_PATH=awtrix3-v${{ needs.create-release.outputs.version }}-${{ matrix.target }}.zip" >> $env:GITHUB_ENV

      - name: Generate checksums
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            sha256sum "${{ env.ASSET_PATH }}" > "${{ env.ASSET_PATH }}.sha256"
          else
            shasum -a 256 "${{ env.ASSET_PATH }}" > "${{ env.ASSET_PATH }}.sha256"
          fi
        shell: bash

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: ${{ env.ASSET_PATH }}
          asset_content_type: application/octet-stream

      - name: Upload Release Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}.sha256
          asset_name: ${{ env.ASSET_PATH }}.sha256
          asset_content_type: text/plain

  upload-install-scripts:
    name: Upload Installation Scripts
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Unix Install Script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: install.sh
          asset_name: install.sh
          asset_content_type: text/plain

      - name: Upload Windows Install Script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: install.ps1
          asset_name: install.ps1
          asset_content_type: text/plain

      - name: Upload Homebrew Formula
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: Formula/awtrix3.rb
          asset_name: awtrix3.rb
          asset_content_type: text/plain

  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: [create-release, build-release]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true  # May fail if version already exists